name: Train ML Model

on:
  push:
    branches:
      - master
    paths:
      - 'MLProject/**'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          environment-file: MLProject/conda.yaml
          activate-environment: msml_env

      - name: Run MLflow Project
        run: |
          cd MLProject
          mlflow run .        # ← tanpa --no-conda
